Default: &defaults
  user: yesodweb
  password: yesodweb
  host: localhost
  port: 5432
  database: yesodweb
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: yesodweb_test
  <<: *defaults

Staging:
  database: yesodweb_staging
  poolsize: 100
  <<: *defaults

Production:
  database: yesodweb_production
  poolsize: 100
  <<: *defaults