Default: &defaults
  host: "127.0.0.1"
  port: 3000
  authors:
    michael:
      name: Michael Snoyman
      email: michael@snoyman.com
    greg:
      name: Greg Weber
      email: greg@gregweber.info

Development:
  <<: *defaults
  approot: ""

Test:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://www.yesodweb.com"
  <<: *defaults
