Default: &defaults
  host: "127.0.0.1"
  port: 3000
  copyright: Insert copyright statement here

Development:
  <<: *defaults
  approot: ""

Test:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://www.yesodweb.com"
  <<: *defaults
